// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteAction(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteAction'](arg1, arg2, arg3);
}

export function GetActions() {
  return window['go']['main']['App']['GetActions']();
}

export function GetActionsForAlert(arg1, arg2) {
  return window['go']['main']['App']['GetActionsForAlert'](arg1, arg2);
}

export function GetAlerts() {
  return window['go']['main']['App']['GetAlerts']();
}

export function GetDisplayConfig() {
  return window['go']['main']['App']['GetDisplayConfig']();
}

export function GetSeverityCounts() {
  return window['go']['main']['App']['GetSeverityCounts']();
}

export function GetUIConfig() {
  return window['go']['main']['App']['GetUIConfig']();
}

export function SetProviders(arg1) {
  return window['go']['main']['App']['SetProviders'](arg1);
}

export function SilenceAlert(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SilenceAlert'](arg1, arg2, arg3, arg4);
}

export function Unsilence(arg1, arg2) {
  return window['go']['main']['App']['Unsilence'](arg1, arg2);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
