// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {model} from '../models';

export function GetActions():Promise<Array<config.ActionConfig>>;

export function GetAlerts():Promise<Array<model.Alert>>;

export function GetDisplayConfig():Promise<config.DisplayConfig>;

export function GetSeverityCounts():Promise<model.SeverityCounts>;

export function GetUIConfig():Promise<config.UIConfig>;
