// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetActions() {
  return window['go']['main']['App']['GetActions']();
}

export function GetAlerts() {
  return window['go']['main']['App']['GetAlerts']();
}

export function GetDisplayConfig() {
  return window['go']['main']['App']['GetDisplayConfig']();
}

export function GetSeverityCounts() {
  return window['go']['main']['App']['GetSeverityCounts']();
}

export function GetUIConfig() {
  return window['go']['main']['App']['GetUIConfig']();
}
