// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {model} from '../models';
import {provider} from '../models';

export function ExecuteAction(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetActions():Promise<Array<config.ActionConfig>>;

export function GetActionsForAlert(arg1:string,arg2:string):Promise<Array<config.ActionConfig>>;

export function GetAlerts():Promise<Array<model.Alert>>;

export function GetDisplayConfig():Promise<config.NormalizedDisplayConfig>;

export function GetNotificationPermissionStatus():Promise<string>;

export function GetOnCallStatus():Promise<Array<model.OnCallStatus>>;

export function GetSeverityConfig():Promise<config.NormalizedSeverityConfig>;

export function GetSeverityCounts():Promise<model.SeverityCounts>;

export function GetSourcesHealth():Promise<Array<model.SourceHealth>>;

export function GetUIConfig():Promise<config.UIConfig>;

export function LayoutPopup(arg1:number,arg2:number,arg3:number,arg4:number,arg5:number):Promise<void>;

export function OpenNotificationSettings():Promise<void>;

export function ResolveDiff(arg1:model.Diff):Promise<model.Diff>;

export function SetProviders(arg1:Record<string, provider.Provider>):Promise<void>;

export function SilenceAlert(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function TestNotificationForAlert(arg1:string,arg2:string):Promise<void>;

export function Unsilence(arg1:string,arg2:string):Promise<void>;

export function UpdateConfig(arg1:config.Config):Promise<void>;
